apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: user-management
  name: user-management
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-management
  template:
    metadata:
      labels:
        app: user-management
        build_number: ${BUILD_NUMBER}
        role: rolling-update
    spec:
      containers:
      - image: 192.168.1.2:5000/user-management:beta
        imagePullPolicy: Always
        name: user-management
      imagePullSecrets:
      - name: mydockercredentials
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 1
